# Thanks to https://raw.githubusercontent.com/jenkinsci/.github/master/.github/release-drafter.yml
# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_MINOR_VERSION
tag-template: $NEXT_MINOR_VERSION
# Uses a more common 2-digit versioning in Jenkins plugins. Can be replaced by semver: $MAJOR.$MINOR.$PATCH
version-template: $MAJOR.$MINOR

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: ğŸš¨ Removed
    label: removed
  - title: âš ï¸ Deprecated
    label: deprecated
  - title: ğŸš€ New features and improvements
    labels:
      - enhancement
      - feature
  - title: ğŸ› Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
   # Default label used by Dependabot
  - title: ğŸ“¦ Dependency updates
    label: dependencies
  - title: ğŸ“ Documentation updates
    label: documentation
  - title: ğŸ‘» Maintenance
    labels:
      - chore
      - internal
  - title: ğŸš¦ Tests
    labels:
      - test
      - tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid


replacers:
  - search: '@dependabot-preview'
    replace: '@dependabot'
